version: "2.1"

services:
  flink:
    image: feathub-flink:latest
    container_name: flink
    networks:
      - flink-hive-network
    command:
      - bash
      - -c
      - |
        export HADOOP_CLASSPATH=`hadoop classpath`
        ./bin/start-cluster.sh; while true; do sleep 10; done
    ports:
      - "8082:8081"
    volumes:
      - "flink_data:/tmp/flink"
      - "./data:/tmp/data"
  hadoop-master:
    image: prestodb/hdp2.6-hive:10
    container_name: hadoop-master
    networks:
      - flink-hive-network
    extra_hosts:
      - hadoop-master:127.0.0.1
    ports:
      - "9083:9083"
    volumes:
      - "./core-site.xml:/usr/hdp/2.6.5.0-292/hadoop/conf/core-site.xml"

networks:
  flink-hive-network:
    name: flink-hive-network

volumes:
  flink_data:
    driver: local
